In [3]:
from collections import Counter

# 샘플 코퍼스
corpus = ["자연어 처리는 재미있다.", "자연어 처리는 컴퓨터 과학의 한 분야다.", "데이터 분석은 자연어 처리와 밀접하다."]

# 단어 단위로 코퍼스를 분리
tokenized_corpus = [sentence.split() for sentence in corpus]
flat_tokens = [word for sentence in tokenized_corpus for word in sentence]

# 단어 빈도 분석
word_freq = Counter(flat_tokens)
print("단어 빈도 분석 결과:", word_freq)

단어 빈도 분석 결과: Counter({'자연어': 3, '처리는': 2, '재미있다.': 1, '컴퓨터': 1, '과학의': 1, '한': 1, '분야다.': 1, '데이터': 1, '분석은': 1, '처리와': 1, '밀접하다.': 1})


In [8]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...


True

In [9]:
from nltk.corpus import wordnet  # 영어 어휘/의미 사전

# Synset 사용 예제
word = "bank"
synsets = wordnet.synsets(word)  # synsets() : word 에 해당하는 모든 의미 리스트 반환
for syn in synsets:
    print(f"뜻: {syn.definition()}")  # 해당 설명 문장 출력

뜻: sloping land (especially the slope beside a body of water)
뜻: a financial institution that accepts deposits and channels the money into lending activities
뜻: a long ridge or pile
뜻: an arrangement of similar objects in a row or in tiers
뜻: a supply or stock held in reserve for future use (especially in emergencies)
뜻: the funds held by a gambling house or the dealer in some gambling games
뜻: a slope in the turn of a road or track; the outside is higher than the inside in order to reduce the effects of centrifugal force
뜻: a container (usually with a slot in the top) for keeping money at home
뜻: a building in which the business of banking transacted
뜻: a flight maneuver; aircraft tips laterally about its longitudinal axis (especially in turning)
뜻: tip laterally
뜻: enclose with a bank
뜻: do business with a bank or keep an account at a bank
뜻: act as the banker in a game or in gambling
뜻: be in the banking business
뜻: put into a bank account
뜻: cover with ashes so to control the rate 

In [ ]:
import re

# 원시 텍스트
raw_text = "Hello!!! 자연어 처리 is FUN.   Do you agree? :)"

# 불필요한 기호 제거 (정규표현식 문법 ^:not \w : 문자,숫자,_ \s : 공백)
clean_text = re.sub(r"[^\w\s]", "", raw_text)

# 소문자 변환
clean_text = clean_text.lower()

# 공백 제거
clean_text = " ".join(clean_text.split())

print("처리된 텍스트:", clean_text)

처리된 텍스트: hello 자연어 처리 is fun do you agree


In [15]:
import nltk
nltk.download('punkt')

# NLTK 최신 버전(3.9 이상)을 사용 중이시라면 아래 코드도 함께 실행해 주세요.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [16]:
from nltk.tokenize import sent_tokenize

text = "자연어 처리는 재미있다! 하지만 배우기는 어렵다. Python으로 가능합니다."
print(sent_tokenize(text))

['자연어 처리는 재미있다!', '하지만 배우기는 어렵다.', 'Python으로 가능합니다.']


In [18]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [21]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

# 원시 텍스트
raw_text = "자연어 처리는 데이터 과학의 한 분야다! 여러 전처리가 필요하다."

# 특수문자 제거 (!, ., ? 등)
clean_text = raw_text.translate(str.maketrans("", "", string.punctuation))

# 숫자 제거 (\d+ : 0부터 9까지의 모든 숫자들)
clean_text = re.sub(r"\\d+", "", clean_text)

# 불용어 제거
tokens = word_tokenize(clean_text)
# stop_words = set(stopwords.words("korean"))
stop_words = {'은', '는', '이', '가', '을', '를', '의', '하다'}
filtered_tokens = [word for word in tokens if word not in stop_words]

print("전처리 결과:", filtered_tokens)

전처리 결과: ['자연어', '처리는', '데이터', '과학의', '한', '분야다', '여러', '전처리가', '필요하다']


In [24]:
import nltk

nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
from konlpy.tag import Okt

# 텍스트
text = "자연어 처리는 정말 재미있다!"

# 형태소 분석
okt = Okt()  # 객체 생성 (= 형태소 분석기 가져옴)
morphs = okt.morphs(text)  # 최소 의미 단위 리스트 분리
pos = okt.pos(text)  # (형태소, 품사) 튜플 리스트로 품사 태깅 작업

print("형태소 분석 결과:", morphs)
print("품사 태깅 결과:", pos)

형태소 분석 결과: ['자연어', '처리', '는', '정말', '재미있다', '!']
품사 태깅 결과: [('자연어', 'Noun'), ('처리', 'Noun'), ('는', 'Josa'), ('정말', 'Noun'), ('재미있다', 'Adjective'), ('!', 'Punctuation')]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 샘플 데이터
corpus = ["자연어 처리는 재미있다.", "자연어 처리는 어렵다.", "데이터는 유용하다."]

# Bag-of-Words
vectorizer = CountVectorizer()  # BoW 백터라이저 생성
bow = vectorizer.fit_transform(corpus)  # 단어사전 학습 (생성)
print("Bag-of-Words:\\n", bow.toarray())

# TF-IDF
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(corpus)
print("TF-IDF:\\n", tfidf_matrix.toarray())

Bag-of-Words:\n [[0 0 0 1 1 1]
 [0 1 0 1 0 1]
 [1 0 1 0 0 0]]
TF-IDF:\n [[0.         0.         0.         0.51785612 0.68091856 0.51785612]
 [0.         0.68091856 0.         0.51785612 0.         0.51785612]
 [0.70710678 0.         0.70710678 0.         0.         0.        ]]


In [2]:
# 샘플 텍스트
text = "자연어 처리는 재미있다. 자연어는 어렵지만 재미있다."

# 단어 빈도 계산
from collections import Counter
words = text.split()
word_count = Counter(words)

# 문장 길이 계산
sentences = text.split(". ")
sentence_lengths = [len(sentence.split()) for sentence in sentences]

print("단어 빈도:", word_count)
print("문장 길이:", sentence_lengths)

단어 빈도: Counter({'재미있다.': 2, '자연어': 1, '처리는': 1, '자연어는': 1, '어렵지만': 1})
문장 길이: [3, 3]


In [5]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 임의의 단어 벡터
word1 = np.array([[1, 2, 3]])
word2 = np.array([[2, 3, 4]])

# 코사인 유사도 계산
similarity = cosine_similarity(word1, word2)  # 결과가 1x1 행렬
print("코사인 유사도:", similarity[0][0])      # 행렬에서 스칼라 값만 출력

코사인 유사도: 0.9925833339709303


In [ ]:
class CNNClassifier(nn.Module):
    def __init__(self, vocab_size, embed_size, num_classes):
        super(CNNClassifier, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.conv = nn.Conv2d(1, 100, (3, embed_size))  # 3-gram 필터
        self.fc = nn.Linear(100, num_classes)

    def forward(self, x):
        x = self.embedding(x).unsqueeze(1)  # 채널 추가
        x = torch.relu(self.conv(x)).squeeze(3)
        x = torch.max(x, dim=2)[0]  # Max pooling
        x = self.fc(x)
        return x

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

# 데이터 준비
corpus = ["자연어 처리는 재미있다", "Python은 강력하다"]
labels = [[1, 0], [0, 1]]  # 다중 레이블

# 모델 정의
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
model = OneVsRestClassifier(LogisticRegression())
model.fit(X, labels)

# 예측
print(model.predict(vectorizer.transform(["Python이 재미있다"])))